-- Agent1c.ai Telegram relay schema (tab-online model)
-- Apply this to project gkfhxhrleuauhnuewfmw before using Telegram relay functions.

create table if not exists public.telegram_link_challenges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  start_code text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_telegram_link_challenges_user
  on public.telegram_link_challenges (user_id, expires_at desc);

create table if not exists public.telegram_links (
  user_id uuid primary key references auth.users(id) on delete cascade,
  telegram_user_id bigint not null unique,
  telegram_chat_id bigint not null,
  telegram_username text,
  telegram_first_name text,
  telegram_last_name text,
  status text not null default 'linked',
  linked_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_telegram_links_tg_user
  on public.telegram_links (telegram_user_id);

create table if not exists public.telegram_inbox (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  telegram_user_id bigint not null,
  telegram_chat_id bigint not null,
  telegram_message_id bigint,
  telegram_username text,
  telegram_first_name text,
  message_text text not null,
  raw_update jsonb,
  created_at timestamptz not null default now(),
  processing_at timestamptz,
  delivered_at timestamptz,
  reply_text text
);

create index if not exists idx_telegram_inbox_user_pending
  on public.telegram_inbox (user_id, delivered_at, processing_at, created_at);

create unique index if not exists idx_telegram_inbox_unique_msg
  on public.telegram_inbox (telegram_chat_id, telegram_message_id);
